const C=window.MK_CONFIG;
const sb=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);
const app=document.getElementById("app");
const admin=location.search.toLowerCase().includes("admin");
const eventDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:C.TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const fmtTime=ts=>new Intl.DateTimeFormat("de-DE",{timeZone:C.TIMEZONE,hour:"2-digit",minute:"2-digit"}).format(new Date(ts));
function hourBerlin(){return Number(new Intl.DateTimeFormat("en-US",{timeZone:C.TIMEZONE,hour:"2-digit",hour12:false}).format(new Date()));}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function bg(){const x=document.createElement("div");x.className="bg";document.body.appendChild(x)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function pageCustomer(){bg();const closed=hourBerlin()>=C.CLOSE_HOUR;app.innerHTML=`<main class="customer"><section class="phone"><div class="top"><img class="logo" src="BB-Logo-2026-260114 1.png"></div><div class="kicker">THIRSTY THURSDAY</div><h1>MYSTERY<span>KEG</span></h1>${closed?`<div class="closed"><div class="check">✓</div><h2>TEILNAHME GESCHLOSSEN</h2><p>Die Verlosung hat bereits um 20 Uhr stattgefunden.<br>Viel Glück beim nächsten Mystery Keg!</p></div>`:`<p class="lead">Errate den Bierstil und gewinne eins von zwei brandneu releasten Premium-Bieren!</p><form class="form-card" id="mkform"><div class="field"><label for="name">Dein Name</label><input id="name" autocomplete="name" maxlength="80" required placeholder="Name eingeben …"></div><div class="field"><label for="style">Bierstil</label><input id="style" maxlength="80" required placeholder="z. B. IPA, Stout, Lager …"></div><button class="primary" id="submit">JETZT TEILNEHMEN! ›</button><div class="note">Teilnahme bis 20:00 Uhr · Verlosung um 20 Uhr</div></form>`}</section></main>`;const f=document.getElementById("mkform");if(f)f.onsubmit=submitEntry}
async function submitEntry(e){e.preventDefault();const b=document.getElementById("submit"),name=document.getElementById("name").value.trim(),style=document.getElementById("style").value.trim();if(!name||!style)return;b.disabled=true;b.textContent="WIRD GESPEICHERT …";if(hourBerlin()>=C.CLOSE_HOUR){pageCustomer();return}const{error}=await sb.from("mystery_keg_entries").insert({event_date:eventDate(),name,beer_style:style});if(error){console.error(error);b.disabled=false;b.textContent="NOCHMAL VERSUCHEN";toast("Teilnahme konnte nicht gespeichert werden.");return}app.innerHTML=`<div class="bg"></div><main class="customer"><section class="phone success"><img class="logo" src="BB-Logo-2026-260114 1.png"><div class="check">✓</div><h2>VIELEN DANK!</h2><p>Deine Teilnahme wurde erfolgreich gespeichert.</p><p><b>Viel Glück!</b><br>Die Verlosung findet um 20 Uhr statt.</p><button class="secondary" onclick="pageCustomer()">↻ NOCHMAL TEILNEHMEN</button></section></main>`}
function adminLogin(){bg();app.innerHTML=`<main class="customer"><section class="phone"><div class="top"><img class="logo" src="BB-Logo-2026-260114 1.png"></div><div class="kicker">BEYOND BEER · INTERNAL</div><h1>MYSTERY<span>KEG</span></h1><form class="form-card" id="login"><div class="field"><label>E-Mail</label><input id="email" type="email" autocomplete="username" required placeholder="Admin E-Mail"></div><div class="field"><label>Passwort</label><input id="password" type="password" autocomplete="current-password" required placeholder="Passwort"></div><button class="primary">ADMIN EINLOGGEN ›</button><p class="note">Nur für Beyond Beer Team.</p></form></section></main>`;document.getElementById("login").onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent="WIRD EINGELOGGT …";const{error}=await sb.auth.signInWithPassword({email:document.getElementById("email").value.trim(),password:document.getElementById("password").value});if(error){toast("Login fehlgeschlagen. E-Mail oder Passwort prüfen.");b.disabled=false;b.textContent="ADMIN EINLOGGEN ›";return}adminPage()}}
async function getEntries(){const{data,error}=await sb.from("mystery_keg_entries").select("*").eq("event_date",eventDate()).order("created_at",{ascending:true});if(error)throw error;return data||[]}
function adminPage(){bg();app.innerHTML=`<main class="admin-page"><section class="admin"><header class="admin-head"><div><img class="admin-logo" src="BB-Logo-2026-260114 1.png"><div class="admin-title">MYSTERY KEG</div><div class="admin-sub">${eventDate()} · iPad Admin</div></div><span class="pill">LIVE</span></header><div id="err"></div><div class="stats"><div class="stat"><b id="count">–</b><span>Teilnehmer</span></div><div class="stat"><b>20:00</b><span>Verlosung</span></div><div class="stat"><b id="win">–</b><span>Gewinner</span></div></div><div class="actions"><button class="tool cyan" onclick="refresh()">↻ AKTUALISIEREN</button><button class="tool" onclick="chooseWinner()">🎲 GEWINNER AUSWÄHLEN</button><button class="tool" onclick="showQR()">▣ QR CODE</button><button class="tool" onclick="downloadCSV()">⇩ CSV EXPORT</button></div><div class="table-wrap"><table><thead><tr><th>UHRZEIT</th><th>NAME</th><th>BIERSTIL</th><th>STATUS</th></tr></thead><tbody id="rows"></tbody></table></div></section></main>`;refresh();sb.channel("mk-live").on("postgres_changes",{event:"*",schema:"public",table:"mystery_keg_entries"},()=>refresh()).subscribe()}
async function refresh(){const rows=document.getElementById("rows");if(!rows)return;try{const data=await getEntries();document.getElementById("count").textContent=data.length;const winner=data.find(e=>e.is_winner);document.getElementById("win").textContent=winner?winner.name:"–";rows.innerHTML=data.length?data.map(e=>`<tr class="${e.is_winner?"winner":""}"><td>${fmtTime(e.created_at)}</td><td>${esc(e.name)}</td><td>${esc(e.beer_style)}</td><td>${e.is_winner?'<span class="winner-badge">🏆 GEWINNER</span>':''}</td></tr>`).join(""):`<tr><td colspan="4" class="empty">Noch keine Teilnahmen.</td></tr>`}catch(e){document.getElementById("err").innerHTML='<div class="error">Admin-Login erforderlich.</div>'}}
async function chooseWinner(){const data=await getEntries();if(!data.length){toast("Noch keine Teilnehmer.");return}if(!confirm(`Aus ${data.length} Teilnehmern zufällig einen Gewinner auswählen?`))return;const{data:w,error}=await sb.rpc("choose_mystery_keg_winner",{p_event_date:eventDate()});if(error){toast("Gewinner konnte nicht ausgewählt werden.");return}await refresh();toast(`🏆 Gewinner: ${(w?.[0]||w)?.name||"ausgewählt"}`)}
function showQR(){const modal=document.createElement("div");modal.className="modal";modal.innerHTML=`<div class="modal-card"><h2>MYSTERY KEG QR</h2><canvas id="qr"></canvas><p style="color:#aeb9bc">QR-Code für die Kundenansicht</p><button class="tool cyan" onclick="this.closest('.modal').remove()">SCHLIESSEN</button></div>`;document.body.appendChild(modal);QRCode.toCanvas(document.getElementById("qr"),location.origin+location.pathname,{width:280,margin:2})}
async function downloadCSV(){const data=await getEntries();if(!data.length){toast("Keine Daten.");return}const csv=["Uhrzeit,Name,Bierstil",...data.map(e=>`"${fmtTime(e.created_at)}","${String(e.name).replaceAll('"','""')}","${String(e.beer_style).replaceAll('"','""')}"`)].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`mystery-keg-${eventDate()}.csv`;a.click()}
window.refresh=refresh;window.chooseWinner=chooseWinner;window.showQR=showQR;window.downloadCSV=downloadCSV;window.pageCustomer=pageCustomer;
if(admin){sb.auth.getSession().then(({data})=>data.session?adminPage():adminLogin())}else pageCustomer();